### ISSUE TITLE
Rocket Racoon

### ISSUE THREAD

**Issue by GoldenFoxMiner** [malonnnn/ServerConfig#1181]
can you give rocket Strength 3, run 4,  jump 4, /fly and guns

**Comment by malonnnn** [comment]
peak human strength is strength level 2. I dont think rocket is stronger than a body builder unless you have evidence?

peak human speed is 27 mph. Racoons can run top speed of 15mph. No run either, unless you have evidence maybe?

peak human humping is jump 2. racoons cannot jump as far as i can tell, unless you have evidence maybe?

He has been given guns :D
