### ISSUE TITLE
Complicated Project for Malon

### ISSUE THREAD

**Issue by Chief-Sly-Fox** [malonnnn/ServerConfig#1223]
Blue lanterns need a power where when they stand within 10 blocks of a green lantern they can use /bluelanternclense <plr> on any person using a yellow orange black or red lantern. The power would pull up one of those chest gui's like /mindcontrol does where you get to click your option. The victim  (red orange black or yellow lantern player being clensed) would see that gui pop up and be able to click either a barrier, an emerald, or a lapislazuli. Choosing barrier block would kill you, choosing emerald would take you to another gui that has one emerald per green lantern character and choosing lapis would open another gui with a lapis for each blue lantern character. When a blue lantern cleanses someone, that person needs a ring or they'll die, the whole gui thing is because when someone is cleansed they have a new ring. What ik trying to say is that when someone runs the cleanse command on you, you get a gui with three options, green lantern, blue lantern, or no ring. Choosing Green lantern opens another gui displaying the green lantern characters, so you chose which green lantern you are. Same with blue lantern option, it is a lapis item that  displays the names 0f blue lanterns so you can chose one to turn into. If you click the barrior it means you have no ring,  so you die,  and turn into a mortal. See Arteriam before making this command.

**Comment by Chief-Sly-Fox** [comment]
Ask me about it tomorrow ill explain step by step while you make it

**Comment by ViceTOP** [comment]
What he says is right, Blue Lanterns have the power to do that

**Comment by malonnnn** [comment]
okay we can do this, probs skip the gui part cuz thats boring, but ye i can make a cleanse command. show me some links of what cleansing looks like and how it works in the comics or the tv show or whatever

**Comment by Supertre03** [comment]
Were having a conversation? COOL! I just wanted to be apart of it ;) ILU all ! :D

**Comment by malonnnn** [comment]
Are we ever gonna do this?

Boil the power down into 1 sentence/phrase, your explanation is confusing.
