### ISSUE TITLE
We Should Add Something Like Switch Brains

### ISSUE THREAD

**Issue by Supertre03** [malonnnn/ServerConfig#1323]
Its like mind control but instead it switches the player's player if that makes sense, like if I were to /switchbrain RoboCode, Rob would be me and I would be him, when I talk its in his chat, I also would have his powers and hero, I bet you get it now... I think at least... I don't know.

**Comment by Supertre03** [comment]
I KNOW HOW WE COULD MAKE IT! Ok so its like mind control, when we do /switchbrain <victim> it turns us into the player, and it forces the victim to do /mindcontrol <switchbrainuser> which turns them into us, or something... i don't know.

**Comment by Supertre03** [comment]
Anyone?

**Comment by Supertre03** [comment]
No?

**Comment by Supertre03** [comment]
Fan ta dig.

**Comment by malonnnn** [comment]
this won't work because when you /mindcontrol someone, you become that person. if that person then does /mindcontrol, they will only be mindcontrolling themselves cuz the other person is them already
