### ISSUE TITLE
For Robo

### ISSUE THREAD

**Issue by TotallyUneffable** [malonnnn/ServerConfig#1520]
Quick message, I won't be on until another 2 and a bit weeks. Soz for it but if you have any urgencies email ner_harrow@hotmail.com (P.S. Let me know first if I DO get kicked out from my position)

**Comment by malonnnn** [comment]
just so you know, you just made ur email address public. This isn't a private message to me, you posted that for everyone to see.

And yes, you've lost your position until you can play more frequently, sorry about that, it's just how it goes. Hope to see you on the server soon!

**Comment by malonnnn** [comment]
hope to see you soon!

**Comment by malonnnn** [comment]
Are you ever coming back to the server?

I've been waiting for your skin expertise :P
