### ISSUE TITLE
more than meets the idea

### ISSUE THREAD

**Issue by Scrabdusan** [malonnnn/ServerConfig#1688]
So hi I'm Scrabdusan. I play on the server a lot. I just came up with a new character idea. I would like to see the transformers as a playable character. If you can get a car  and plane mod then fine. 
here are the characters I'd like to see:
Bumblebee
Optimus Prime
Ironhide
Megatron
Starscream
If you can't make them all then its OK. To help I added a transformers skin link. I can't hyperlink so here's the the link http://www.minecraftskins.com/search/skin/transformers/1/

**Comment by Boofurd** [comment]
I just finished making optimus prime, and I will continue working on all of these requests when I have time. Thanks for the idea!

**Comment by jaikev** [comment]
I'm making a few heroes right now because i'm bored
