### ISSUE TITLE
Add Scarlet Witch as a hero

### ISSUE THREAD

**Issue by FireUser** [malonnnn/ServerConfig#1738]
Hey, I'm Fire_User. I think that you should add Scarlet Witch as a hero because you already have her twin, Quicksilver, and he is dead in the movie universe, but Scarlet Witch isn't. I know her powers might be a little hard to add, but you could still add it and I think that would be amazing.
Thanks
-Fire_User

**Comment by ViceTOP** [comment]
Not really hard, reality alteration, magic bolts, teleportation, a bit enhanced strenght. The only hard one would be... Telekinesis, but if coders used the spell plugin, and got Scarlet Witch a wand with the spell push and pull, it would work.
