### ISSUE TITLE
black lantern (ET)

### ISSUE THREAD

**Issue by FireAntG** [malonnnn/ServerConfig#1798]
WHEN I DO /SPEEDFORCEBUFFS IT DONT DO ANYTHING PLEAASE FIX IT

**Comment by Mistoffeles01** [comment]
it only works in the speedforce and it gives u strenght u dont see it osmetimes only if u press e

**Comment by Mistoffeles01** [comment]
*sometimes

**Comment by malonnnn** [comment]
confirmed in game this is a non-issue
