### ISSUE TITLE
All WebSlingers

### ISSUE THREAD

**Issue by Doctorwho11-5** [malonnnn/ServerConfig#1815]
Make it so that when you shoot a web, it stick to something first, you shift to go to it. If it's stuck on a mob and you shift, it brings the mob. Also if you don't want to use websling after you shoot it, like when mining a block or something, just switch hotbar slots.  I'd totally do it, but angel hasn't taught me to code so not sure how to.

**Comment by malonnnn** [comment]
not possible, the leash will snap if you don't get pulled
