### ISSUE TITLE
Sorry but i can't play on this server anymore :( (Click this)

### ISSUE THREAD

**Issue by jaikev** [malonnnn/ServerConfig#1863]
Because i played to much on this server so me and my brother/parents decided to remove it

**Comment by jaikev** [comment]
There was no rule against "Don't share your account to others" well i don't go the riches family ever so we got importer things to do then buy two accounts

**Comment by jaikev** [comment]
btw, I removed Minecraft

**Comment by jaikev** [comment]
From D_SuperGirl_C

**Comment by malonnnn** [comment]
aw dang, thats too bad

well, if you can ever play again, hope to see you!! :D
