### ISSUE TITLE
New Death Ray Ability

### ISSUE THREAD

**Issue by yYKirbyYy** [malonnnn/ServerConfig#1898]
I have an idea for an ability that is incredibly cool, yet incredibly overpowered. It is a diamond horse armor that when you right click it, it lets off a huge constant laser that on impact with walls, ground, ceiling, or most importantly, players, it explodes. 

Example: >============================{{{}}}l
                gun: >                     laser: =                      explosion: {{{}}}    wall: l

I don't yet know what hero this should be added to, but it is a very cool ability nonetheless.

**Comment by yYKirbyYy** [comment]
This should be in Pull Requests, my bad.

**Comment by malonnnn** [comment]
this is very cool, but unfortunately this doesnt belong to a hero so it won't be added. We don't just make up new powers here, we use existing heroes powers sorry :(

**Comment by yYKirbyYy** [comment]
This ability would be for a hero named Vel'koz. Based off of a champion form the MOBA (multiplayer online battle arena) League of Legends. This hero is pretty much a floating purple eye with tentacles that can fire lasers. Some of its abilities could include: making a geyser of lasers explode through the ground, shooting a homing laser ball, and the before-mentioned death ray.

![image](https://cloud.githubusercontent.com/assets/25909782/23139062/971b05e0-f778-11e6-96a5-953a02ff0c57.png)

![vkc](https://cloud.githubusercontent.com/assets/25909782/23139094/b90828c2-f778-11e6-9533-45df873459c1.jpg)
Top right: Death Ray
Bottom right: Laser geyser
Bottom middle: Homing laser
Bottom left: Character Model
(Note: these pictures are just for reference if needed. Other info can be found on google)

**Comment by yYKirbyYy** [comment]
Revised: Scratch Vel'Koz, This ability would be added to a hero from the same game: Xerath
