### ISSUE TITLE
New Suggestion A CO-OP Feature

### ISSUE THREAD

**Issue by Hoprocker08** [malonnnn/ServerConfig#1979]
I often find myself on with just one or 2 other people who wont pvp because they know the chacter I play with is over powered. This leaves me extremely bored. I think there should be a CO-OP feature were people can fight together against mobs like buffed mobs with hard hits and lots of health the further you get into it. There could be a level system were is gets progressively harder to beat levels!

**Comment by malonnnn** [comment]
this could be a lot of fun.

how should we get started?

**Comment by ZargonKing** [comment]
We would need a co-op type map and a custom mob plugin; https://dev.bukkit.org/projects/custom-mobs
