### ISSUE TITLE
PRs

### ISSUE THREAD

**Issue by Leedler268** [malonnnn/ServerConfig#2655]
I dunno if the engineers are getting lazy or something, but nobody's checking the prs. AT ALL.

**Comment by Supertre03** [comment]
Well, I think the only person that can actually put the code inside the server is Tektronix, Malonnnn, God_Doesnt_Exist, RoboTek, or whatever you call the server owner now. Engineers probably look at the code, but they can't actually put it in the code if you know what I mean.
